const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "AYANFE 🌹",
    ownerNumber: process.env.OWNER_NUMBER || "2347079115653",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "false",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib083S1IrRjdRRTAyT3ZSRWh1VmtSWXI2VU5HeFFsN3RRY0RndnViUmVIMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRTI3Ry84MjVHRmZBVWVKUXNZQ3ZNWGFBVHNtNXRqYnZqTC9EdEtNZmVIcz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4REU1clM5ckNIUEVjSU9Ld0N0ODV5V0Nka1FnSE05ZHI2TXpnbDRncmwwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJqS3UxaXFUOUlxU2YvTHlxc05DcWwyNnlSZXRYQVVCVlBta3dWTkJnQncwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZBWFJsRERUYW1lc1BRYko3VGRQSXpoZ1pKaENuT3VLWlAxYUtHeVdnSDA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdXNnFSMzY2Ry9od1I1dUpVb1M0MENJdUVOZ0piYVMraVR2QmdBSWNGVnc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiME1ONUZ2aHcwdEllbUZCeFJ6djhBOVpWQTAvRC9jb0VWMEdsdjVQNmNrcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaTg4T1Zram01djRRc3AwenlqcGNMMC9BZDUwazBFdGhoelE0eFlMb3FWRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1wT0ZlREhQV1FaMXRoVXF6MHdZVmtkZnlWY2ErYmNCQ1I1VE1rQUdLQnJ3c0FxcXM5c3QyOGVRYy82VHZBU2p3bDNYL2szZUUwdWN4dDA2QlkvZmlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjgsImFkdlNlY3JldEtleSI6IitBZW02aG00VHBLc0IydG9VNHhSREptNjFEckdHb2ZuUDFSNGNOQ0RqNzQ9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IkM4TU1CM01ZIiwibWUiOnsiaWQiOiIyMzQ3MDc5MTE1NjUzOjJAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIyNDM1NzQ5ODA2Mjc3OjJAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNJR3UzTndERVB6eXhMMEdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI4RklTR2Z1b1Z6NExGa0dtYUFpWnY3L2k1QVFMQmRVMkwxcnQyT2l3a1gwPSIsImFjY291bnRTaWduYXR1cmUiOiJWakFFMGZ2NlpNMXJCVEw1aGtiOGdzem1zOVI1eGRJMDhyaGFKeE1zZm4zSWZ5UEVEcHRFbE1EWjhBd1ZaeWdyNFIvVTFMY3BKWmFJMmF2RWphYUlDdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiSWdYOUJvamVtS1NnNXFldWFmdGhiczJveU1EKy9GUnp6K2ljcTc3SFJ4Wmw3NzJLRUh5WTBGV2VUbWllcmJaY29DYmlyVlQ2RURES0RMU2VaRjdIZ1E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ3MDc5MTE1NjUzOjJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZkJTRWhuN3FGYytDeFpCcG1nSW1iKy80dVFFQ3dYVk5pOWE3ZGpvc0pGOSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSUVnPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM5NjY3ODUwLCJsYXN0UHJvcEhhc2giOiIyUDFZaGYifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
